#!/bin/bash


createStructure() {
  #### Creating directory structure:
  if [[ -d $CADIR ]]; then
    echo "Directory $CADIR exists and may contain important files. Remove it? [Y/n]."

    while read -s -n1 answer; do
      if [[ $answer == [Nn] ]]; then
        exit -1
      elif [[ $answer == [Yy] ]]; then
        rm -rf $CADIR
        rm ./conf/ca-ssl-default.conf
        rm ./conf/ssl-default.conf
  
        break
      else
        (>&2 echo -e "\n\nPlease type y or n:\n") 
      fi
    done

  fi

  mkdir -p $CADIR/private
  mkdir -p $CADIR/certs
}


setupCA() {
  #### Sets the default openssl.cnf x509 fields.
  
  echo -e "\n\nPlease provide the default information for your root CA:\n\n"
  echo -n "Country Name (2 letter code): "
  read countryName_default
  echo -n "State or Province Name (full name): "
  read stateOrProvinceName_default
  echo -n "Locality Name (eg, city): "
  read localityName_default
  echo -n "Organization Name (eg, company): "
  read organizationName_default
  echo -n "Organizational Unit Name (eg, section): "
  read organizationalUnitName_default
  echo -n "Common Name (eg, Internal Root Certification Authority): "
  read commonName_default
  echo -n "Email Address: "
  read emailAddress_default

  #### create ca-ssl-default.cnf file:
  TEMPLATE=$HOMEDIR/conf/ca-ssl-default.conf.tmpl
  sed -e "s/@@_countryName_default_@@/$countryName_default/g" \
      -e "s/@@_stateOrProvinceName_default_@@/$stateOrProvinceName_default/g" \
      -e "s/@@_localityName_default_@@/$localityName_default/g" \
      -e "s/@@_organizationName_default_@@/$organizationName_default/g" \
      -e "s/@@_organizationalUnityName_default_@@/$organizationalUnitName_default/g" \
      -e "s/@@_commonName_default_@@/$commonName_default/g" \
      -e "s/@@_emailAddress_default_@@/$emailAddress_default/g" \
      $TEMPLATE > $HOMEDIR/conf/ca-ssl-default.conf

  #### create ssl-default.cnf file:
  TEMPLATE=$HOMEDIR/conf/ssl-default.conf.tmpl
  sed -e "s/@@_countryName_default_@@/$countryName_default/g" \
      -e "s/@@_stateOrProvinceName_default_@@/$stateOrProvinceName_default/g" \
      -e "s/@@_localityName_default_@@/$localityName_default/g" \
      -e "s/@@_organizationName_default_@@/$organizationName_default/g" \
      -e "s/@@_organizationalUnityName_default_@@/$organizationalUnitName_default/g" \
      -e "s/@@_commonName_default_@@/$commonName_default/g" \
      -e "s/@@_emailAddress_default_@@/$emailAddress_default/g" \
      $TEMPLATE > $HOMEDIR/conf/ssl-default.conf
}

createCA() {

  #### RSA key pair:
  openssl genrsa \
          -out $CADIR/private/cakey.pem 4096
  
  #### Certificate Sign Request (CSR):
  openssl req \
          -new \
          -config $HOMEDIR/conf/ca-ssl-default.conf \
          -key $CADIR/private/cakey.pem \
          -out $CADIR/cacsr.csr
}

main() {

  HOMEDIR=/root/pki
  CADIR=$HOMEDIR/CA

  createStructure
  setupCA
  createCA
  exit 0
}

####
main

