#!/bin/bash

#
# Please, check for ./conf/ssl-default.conf for default values.
#

checkInput(){
if [[ ! $1 ]]; then
  echo "Usage $0 <certificate file>"
  exit 1
fi

HOMEDIR=/root/pki
CADIR=$HOMEDIR/CA

CERTFILE=$1
fqdn=$2
}

revoke() {
openssl ca \
        -config $HOMEDIR/conf/ssl-default.conf \
        -revoke $CADIR/certs/$fqdn/$CERTFILE

#### Generate a new crl file:
openssl ca \
        -gencrl \
        -keyfile $HOMEDIR/CA/private/cakey.pem \
        -cert $HOMEDIR/CA/cacert.pem \
        -config $HOMEDIR/conf/ssl-default.conf \
        -out $CADIR/crl/ca.crl

echo
echo "Please check at $CADIR/index.txt for the Certificate Revoke List."
echo

}

main() {
  checkInput $1 $2
  revoke $CERTFILE
  exit 0
}

####
main $1 $2
